sudo: required

before_install:
- sudo apt-get install zip
- sudo apt install ccache
- sudo apt install liblz4-tool
- git clone --recursive https://github.com/TheRagingBeast/A6000_TheRagingBeast -b dms ~/trb
- git clone git clone https://github.com/DhirajSurvase/GCC_4.8 ~/trb/tc
script:
- cd ~/trb
- chmod a+x ~/trb/tc
- chmod a+x ~/trb/tc/bin
- sudo chmod -R 755 ~/trb
- export ARCH=arm
- export CROSS_COMPILE=~/trb/tc/bin/arm-eabi-
- export KBUILD_BUILD_USER="JonnyS"
- export KBUILD_BUILD_HOST="TheScorpion"
- make lineageos_a6000_defconfig
- make -j128
- cp ~/trb/arch/arm/boot/zImage ~/trb/lf
- cd ~/trb/lf
- zip -r TheRagingBeast_a6000-CIBuild.zip *
- curl --upload-file ./TheRagingBeast_a6000-CIBuild.zip https://transfer.sh/TheRagingBeast_a6000-CIBuild.zip
- cd ~/trb/arch/arm/boot
- curl --upload-file ./zImage https://transfer.sh/zImage
- cd ~/trb/lf
- echo All Done
